<a href="https://colab.research.google.com/github/neethj/deep-learning-fundamentals/blob/main/deeplearning_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# learning deep learning with tensor flow

##fundamentals

In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dimensions of a tensor
scalar.ndim

0

In [ ]:
# create vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# dimension of vector

vector.ndim

1

In [ ]:
#create a matrix

matrix = tf.constant([[1,1],
                     [6,9]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [6, 9]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#lets try to use another parameter of tf.constant : dtype

another_matrix = tf.constant([[5., 6.],
                              [1.,6.],
                              [9.,9]],dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[5., 6.],
       [1., 6.],
       [9., 9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# lets make a 3 dimensional tensor

matrix_1 = tf.constant([[[1,2,3],
                         [4,5,6]]])
matrix_1

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
matrix_1.ndim

3

In [ ]:
matrix_2 = tf.constant([[[1,2,3],
                         [3,4,5]],
                         [[7,8,9],
                          [10,11,12]],
                        [[13,14,15],
                         [16,17,18]]])
matrix_2

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
matrix_2.ndim

3

##creating tensors with tf.Variable


In [ ]:
changeable_tensor = tf.Variable([10,1])
unchangeable_tensor = tf.constant([10,1])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  1], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  1], dtype=int32)>)

In [ ]:
# change the elements in the changeable tensor using assign()

changeable_tensor[0].assign(1)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 1], dtype=int32)>

tensors created with tf.variable can be changed and tensors created with tf.constant cannot be changed


##Creating random tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(12)
random_1 = random_1.normal(shape =(3,2))
random_2 = tf.random.Generator.from_seed(12)
random_2 = random_2.normal(shape = (3,2))

In [ ]:
# are these two random tensors equal??

random_1, random_2, random_1 ==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random_3 = tf.random.Generator.from_seed(12)
random_3 = random_3.normal(shape =(3,3))
random_3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.0130816 ,  0.28291714,  1.2132233 ],
       [ 0.46988967,  0.37944323, -0.6664026 ],
       [ 0.6054596 ,  0.19181173,  0.8045827 ]], dtype=float32)>

### shuffle the order of elements in tensor

In [ ]:
#when u wanna shuffle ur data so the order of the thing dont affect learning

not_shuffled = tf.constant([[10,7],
                           [2,3],
                           [6,7]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 6,  7]], dtype=int32)>

In [ ]:
#shuffle the non shuffled data

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3],
       [ 6,  7]], dtype=int32)>

In [ ]:
not_shuffled_1 = tf.constant([[1,2],
                              [3,4],
                              [5,6]])

In [ ]:
tf.random.set_seed(42) # when u set the seed, the values in the matrix dont change so it will stick to the pattern

tf.random.shuffle(not_shuffled_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled_1,seed =42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

so if the operation level seed is not working , where as the global level seed works !

The main intention behind shuffling the elements is that if the elements are not shuffled, then the neural networks learns only in that specific order. if elements are shuffled then it can learn in all orders and then can differentiate more.

we use seeds to get reproducible randomness


## Other ways to make tensors

In [ ]:
# create tensor of all ones

tf.ones([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### turn numpy arrays into tensors

diff between numpy array and tensorflow tensors is that tensors can run much faster on gpu

In [ ]:
import numpy as np
numpy_A = np.arange(1,25)
numpy_A



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
x = tf.constant(numpy_A)
x

# so when we pass a numpy array into tensor flow constant, it makes a tensor

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
# now lets try changing the shape of the numpy array when we change it to tensor

x =tf.constant(numpy_A, shape =(2,3,4))
x

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [ ]:
tf.constant(numpy_A, shape = (6,4))

# number of elements in the

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

the shape can be changed in a way that the total number of elements in the numpy array, and the shape of the tensor would be numbers that can be multiplied and the same number as total number of elements


## getting more info from tensors

In [ ]:
# tensor attributes to be aware of : shape, rank, axis, size

In [ ]:
# create a rank 4 tensor - 4 dimensions
rank_tensor = tf.zeros(shape=[2,3,4,5])
rank_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_tensor.shape, rank_tensor.ndim, tf.size(rank_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
import numpy as np

In [ ]:
print("Datatype of every element:", rank_tensor.dtype)
print("Number of dimensions", rank_tensor.ndim)
print("Shape of tensor:", rank_tensor.shape)
print("elements along 0 axis:", rank_tensor.shape[0])
print("Elements along last axis:", rank_tensor.shape[-1])
print("total number of elements in our tensor:", tf.size(rank_tensor))
print("total number of elements in our tensor:", tf.size(rank_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions 4
Shape of tensor: (2, 3, 4, 5)
elements along 0 axis: 2
Elements along last axis: 5
total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
total number of elements in our tensor: 120


## indexing tensors

In [ ]:
 rank_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

## expanding existing tensors


In [ ]:
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])
rank_2_tensor.ndim,rank_2_tensor.shape

(2, TensorShape([2, 2]))

 if i wanna get the last item of each row,


In [ ]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

add in an extra dimension

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [ ]:
rank_3_tensor.shape

TensorShape([2, 2, 1])

Alternative to tf. newaxis

In [ ]:
tf.expand_dims(rank_2_tensor, axis = -1) # axis = -1 means it wants to add the dimension after the final dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

## Manipulating tensors

if your data is stored in tensors, then often for finding patterns we need to manipulate tensors

In [3]:
# adding values to tensor using addition operators

tensor = tf.constant([[1,2],[3,4]])
tensor+ 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
tf.add(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>

## matrix multiplication

matrix multiplicaiton is a very common operation in machine learning

we can use @, tensordot and matmul for matrix dot products

In [5]:
print(tensor)
tf.matmul(tensor,tensor)  # this is doing dot product

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [7]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [9]:
tensor @ tensor # @ symbol in python is for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [6]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

In [11]:
tf.matmul(x,y)

InvalidArgumentError: ignored

In [3]:
x1 = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y1 = tf.constant([[1,2],
                 [3,4]])

x1 @ y1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22],
       [23, 34]], dtype=int32)>

In [16]:
y = tf.reshape(y,(2,3))

In [17]:
x @ y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

tf.matmul() and tf.tensordot() both can be used for dot product

In [4]:
tf.transpose(x1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [5]:
tf.reshape(x1, (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

so when yu do transpose the rows become columns and the columns become rows. whereas when we use reshape, the just changes the order of the elements and makes it into the shape that we want

In [7]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [10]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

In [11]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [12]:
tf.matmul(x,tf.reshape(y,(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

changing datatype of tensor

In [13]:
B = tf.constant([1.2,3.2])
B.dtype

tf.float32

In [14]:
c = tf.constant([1,2])
c.dtype

tf.int32

In [16]:
# chanmge float 32 to float 16 , this has reduced precision

D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.2], dtype=float16)>

In [18]:
#change int 32 to float 16

E = tf.cast(c,tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

## Aggregating tensors

aggregating tensors is condensing them from multiple values down to a smaller amount of values

In [21]:
# get the absolute values

N = tf.constant([-1,-2])
N

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>

In [22]:
tf.abs(N)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

aggregation:
 minimum
maximum
 sum
mean

In [25]:
import numpy as np

In [27]:
# create random tensor between 0 and 100 size 50

E = tf.constant(np.random.randint(0,100, 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([19, 12, 52, 11, 95, 55, 13, 43, 86, 83, 17, 55, 82, 42, 64, 83, 14,
       15, 12, 86, 48, 48, 86, 24, 74, 65, 95, 89, 47, 24,  8, 44, 69, 86,
       54, 44, 26,  3, 30, 29, 33, 56, 98, 15, 75, 83, 40, 11, 40, 63])>

In [28]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [29]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [30]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [32]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2446>

In [34]:
tf.math.reduce_variance(E)

TypeError: ignored

In [35]:
E = tf.cast(E, dtype=tf.float32)

In [36]:
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=801.5536>

In [37]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=28.311722>